/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as MetodoRouteImport } from './routes/metodo'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as LiderancaRouteImport } from './routes/lideranca'
import { Route as KorthexExecutivoRouteImport } from './routes/korthex-executivo'
import { Route as IndexRouteImport } from './routes/index'

const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoRoute = MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const LiderancaRoute = LiderancaRouteImport.update({
  id: '/lideranca',
  path: '/lideranca',
  getParentRoute: () => rootRouteImport,
} as any)
const KorthexExecutivoRoute = KorthexExecutivoRouteImport.update({
  id: '/korthex-executivo',
  path: '/korthex-executivo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/korthex-executivo': typeof KorthexExecutivoRoute
  '/lideranca': typeof LiderancaRoute
  '/manifesto': typeof ManifestoRoute
  '/metodo': typeof MetodoRoute
  '/performance': typeof PerformanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/korthex-executivo': typeof KorthexExecutivoRoute
  '/lideranca': typeof LiderancaRoute
  '/manifesto': typeof ManifestoRoute
  '/metodo': typeof MetodoRoute
  '/performance': typeof PerformanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/korthex-executivo': typeof KorthexExecutivoRoute
  '/lideranca': typeof LiderancaRoute
  '/manifesto': typeof ManifestoRoute
  '/metodo': typeof MetodoRoute
  '/performance': typeof PerformanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/korthex-executivo'
    | '/lideranca'
    | '/manifesto'
    | '/metodo'
    | '/performance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/korthex-executivo'
    | '/lideranca'
    | '/manifesto'
    | '/metodo'
    | '/performance'
  id:
    | '__root__'
    | '/'
    | '/korthex-executivo'
    | '/lideranca'
    | '/manifesto'
    | '/metodo'
    | '/performance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KorthexExecutivoRoute: typeof KorthexExecutivoRoute
  LiderancaRoute: typeof LiderancaRoute
  ManifestoRoute: typeof ManifestoRoute
  MetodoRoute: typeof MetodoRoute
  PerformanceRoute: typeof PerformanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo': {
      id: '/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof MetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lideranca': {
      id: '/lideranca'
      path: '/lideranca'
      fullPath: '/lideranca'
      preLoaderRoute: typeof LiderancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/korthex-executivo': {
      id: '/korthex-executivo'
      path: '/korthex-executivo'
      fullPath: '/korthex-executivo'
      preLoaderRoute: typeof KorthexExecutivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KorthexExecutivoRoute: KorthexExecutivoRoute,
  LiderancaRoute: LiderancaRoute,
  ManifestoRoute: ManifestoRoute,
  MetodoRoute: MetodoRoute,
  PerformanceRoute: PerformanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
