/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as MetodoRouteImport } from './routes/metodo'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as LiderancaRouteImport } from './routes/lideranca'
import { Route as KorthexExecutivoRouteImport } from './routes/korthex-executivo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminNovoRouteImport } from './routes/admin.novo'
import { Route as AdminIdRouteImport } from './routes/admin.$id'

const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoRoute = MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const LiderancaRoute = LiderancaRouteImport.update({
  id: '/lideranca',
  path: '/lideranca',
  getParentRoute: () => rootRouteImport,
} as any)
const KorthexExecutivoRoute = KorthexExecutivoRouteImport.update({
  id: '/korthex-executivo',
  path: '/korthex-executivo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNovoRoute = AdminNovoRouteImport.update({
  id: '/admin/novo',
  path: '/admin/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIdRoute = AdminIdRouteImport.update({
  id: '/admin/$id',
  path: '/admin/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/korthex-executivo': typeof KorthexExecutivoRoute
  '/lideranca': typeof LiderancaRoute
  '/manifesto': typeof ManifestoRoute
  '/metodo': typeof MetodoRoute
  '/performance': typeof PerformanceRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/novo': typeof AdminNovoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/korthex-executivo': typeof KorthexExecutivoRoute
  '/lideranca': typeof LiderancaRoute
  '/manifesto': typeof ManifestoRoute
  '/metodo': typeof MetodoRoute
  '/performance': typeof PerformanceRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/novo': typeof AdminNovoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/korthex-executivo': typeof KorthexExecutivoRoute
  '/lideranca': typeof LiderancaRoute
  '/manifesto': typeof ManifestoRoute
  '/metodo': typeof MetodoRoute
  '/performance': typeof PerformanceRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/novo': typeof AdminNovoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/korthex-executivo'
    | '/lideranca'
    | '/manifesto'
    | '/metodo'
    | '/performance'
    | '/admin/$id'
    | '/admin/novo'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/korthex-executivo'
    | '/lideranca'
    | '/manifesto'
    | '/metodo'
    | '/performance'
    | '/admin/$id'
    | '/admin/novo'
    | '/blog/$slug'
    | '/admin'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/korthex-executivo'
    | '/lideranca'
    | '/manifesto'
    | '/metodo'
    | '/performance'
    | '/admin/$id'
    | '/admin/novo'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KorthexExecutivoRoute: typeof KorthexExecutivoRoute
  LiderancaRoute: typeof LiderancaRoute
  ManifestoRoute: typeof ManifestoRoute
  MetodoRoute: typeof MetodoRoute
  PerformanceRoute: typeof PerformanceRoute
  AdminIdRoute: typeof AdminIdRoute
  AdminNovoRoute: typeof AdminNovoRoute
  BlogSlugRoute: typeof BlogSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo': {
      id: '/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof MetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lideranca': {
      id: '/lideranca'
      path: '/lideranca'
      fullPath: '/lideranca'
      preLoaderRoute: typeof LiderancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/korthex-executivo': {
      id: '/korthex-executivo'
      path: '/korthex-executivo'
      fullPath: '/korthex-executivo'
      preLoaderRoute: typeof KorthexExecutivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/novo': {
      id: '/admin/novo'
      path: '/admin/novo'
      fullPath: '/admin/novo'
      preLoaderRoute: typeof AdminNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$id': {
      id: '/admin/$id'
      path: '/admin/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AdminIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KorthexExecutivoRoute: KorthexExecutivoRoute,
  LiderancaRoute: LiderancaRoute,
  ManifestoRoute: ManifestoRoute,
  MetodoRoute: MetodoRoute,
  PerformanceRoute: PerformanceRoute,
  AdminIdRoute: AdminIdRoute,
  AdminNovoRoute: AdminNovoRoute,
  BlogSlugRoute: BlogSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
