/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as MetodoRouteImport } from './routes/metodo'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as LiderancaRouteImport } from './routes/lideranca'
import { Route as KorthexExecutivoRouteImport } from './routes/korthex-executivo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DiagnosticosChaveRouteImport } from './routes/diagnosticos.$chave'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminNovoRouteImport } from './routes/admin.novo'
import { Route as AdminIdRouteImport } from './routes/admin.$id'
import { Route as AdminDiagnosticosIndexRouteImport } from './routes/admin.diagnosticos.index'
import { Route as DiagnosticosChaveMapaRouteImport } from './routes/diagnosticos.$chave_.mapa'
import { Route as AdminDiagnosticosResultadoExemploRouteImport } from './routes/admin.diagnosticos.resultado-exemplo'
import { Route as AdminDiagnosticosIdRouteImport } from './routes/admin.diagnosticos.$id'
import { Route as DiagnosticosChaveLiderIdRouteImport } from './routes/diagnosticos.$chave_.lider.$id'
import { Route as AdminDiagnosticosLiderIdRouteImport } from './routes/admin.diagnosticos.lider.$id'
import { Route as AdminDiagnosticosEmpresaIdRouteImport } from './routes/admin.diagnosticos.empresa.$id'

const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoRoute = MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const LiderancaRoute = LiderancaRouteImport.update({
  id: '/lideranca',
  path: '/lideranca',
  getParentRoute: () => rootRouteImport,
} as any)
const KorthexExecutivoRoute = KorthexExecutivoRouteImport.update({
  id: '/korthex-executivo',
  path: '/korthex-executivo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticosChaveRoute = DiagnosticosChaveRouteImport.update({
  id: '/diagnosticos/$chave',
  path: '/diagnosticos/$chave',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNovoRoute = AdminNovoRouteImport.update({
  id: '/admin/novo',
  path: '/admin/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIdRoute = AdminIdRouteImport.update({
  id: '/admin/$id',
  path: '/admin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDiagnosticosIndexRoute = AdminDiagnosticosIndexRouteImport.update({
  id: '/admin/diagnosticos/',
  path: '/admin/diagnosticos/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticosChaveMapaRoute = DiagnosticosChaveMapaRouteImport.update({
  id: '/diagnosticos/$chave_/mapa',
  path: '/diagnosticos/$chave/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDiagnosticosResultadoExemploRoute =
  AdminDiagnosticosResultadoExemploRouteImport.update({
    id: '/admin/diagnosticos/resultado-exemplo',
    path: '/admin/diagnosticos/resultado-exemplo',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDiagnosticosIdRoute = AdminDiagnosticosIdRouteImport.update({
  id: '/admin/diagnosticos/$id',
  path: '/admin/diagnosticos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticosChaveLiderIdRoute =
  DiagnosticosChaveLiderIdRouteImport.update({
    id: '/diagnosticos/$chave_/lider/$id',
    path: '/diagnosticos/$chave/lider/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDiagnosticosLiderIdRoute =
  AdminDiagnosticosLiderIdRouteImport.update({
    id: '/admin/diagnosticos/lider/$id',
    path: '/admin/diagnosticos/lider/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDiagnosticosEmpresaIdRoute =
  AdminDiagnosticosEmpresaIdRouteImport.update({
    id: '/admin/diagnosticos/empresa/$id',
    path: '/admin/diagnosticos/empresa/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/korthex-executivo': typeof KorthexExecutivoRoute
  '/lideranca': typeof LiderancaRoute
  '/manifesto': typeof ManifestoRoute
  '/metodo': typeof MetodoRoute
  '/performance': typeof PerformanceRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/novo': typeof AdminNovoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/diagnosticos/$chave': typeof DiagnosticosChaveRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/diagnosticos/$id': typeof AdminDiagnosticosIdRoute
  '/admin/diagnosticos/resultado-exemplo': typeof AdminDiagnosticosResultadoExemploRoute
  '/diagnosticos/$chave/mapa': typeof DiagnosticosChaveMapaRoute
  '/admin/diagnosticos/': typeof AdminDiagnosticosIndexRoute
  '/admin/diagnosticos/empresa/$id': typeof AdminDiagnosticosEmpresaIdRoute
  '/admin/diagnosticos/lider/$id': typeof AdminDiagnosticosLiderIdRoute
  '/diagnosticos/$chave/lider/$id': typeof DiagnosticosChaveLiderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/korthex-executivo': typeof KorthexExecutivoRoute
  '/lideranca': typeof LiderancaRoute
  '/manifesto': typeof ManifestoRoute
  '/metodo': typeof MetodoRoute
  '/performance': typeof PerformanceRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/novo': typeof AdminNovoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/diagnosticos/$chave': typeof DiagnosticosChaveRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/diagnosticos/$id': typeof AdminDiagnosticosIdRoute
  '/admin/diagnosticos/resultado-exemplo': typeof AdminDiagnosticosResultadoExemploRoute
  '/diagnosticos/$chave/mapa': typeof DiagnosticosChaveMapaRoute
  '/admin/diagnosticos': typeof AdminDiagnosticosIndexRoute
  '/admin/diagnosticos/empresa/$id': typeof AdminDiagnosticosEmpresaIdRoute
  '/admin/diagnosticos/lider/$id': typeof AdminDiagnosticosLiderIdRoute
  '/diagnosticos/$chave/lider/$id': typeof DiagnosticosChaveLiderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/korthex-executivo': typeof KorthexExecutivoRoute
  '/lideranca': typeof LiderancaRoute
  '/manifesto': typeof ManifestoRoute
  '/metodo': typeof MetodoRoute
  '/performance': typeof PerformanceRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/novo': typeof AdminNovoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/diagnosticos/$chave': typeof DiagnosticosChaveRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/diagnosticos/$id': typeof AdminDiagnosticosIdRoute
  '/admin/diagnosticos/resultado-exemplo': typeof AdminDiagnosticosResultadoExemploRoute
  '/diagnosticos/$chave_/mapa': typeof DiagnosticosChaveMapaRoute
  '/admin/diagnosticos/': typeof AdminDiagnosticosIndexRoute
  '/admin/diagnosticos/empresa/$id': typeof AdminDiagnosticosEmpresaIdRoute
  '/admin/diagnosticos/lider/$id': typeof AdminDiagnosticosLiderIdRoute
  '/diagnosticos/$chave_/lider/$id': typeof DiagnosticosChaveLiderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/korthex-executivo'
    | '/lideranca'
    | '/manifesto'
    | '/metodo'
    | '/performance'
    | '/admin/$id'
    | '/admin/novo'
    | '/blog/$slug'
    | '/diagnosticos/$chave'
    | '/admin/'
    | '/blog/'
    | '/admin/diagnosticos/$id'
    | '/admin/diagnosticos/resultado-exemplo'
    | '/diagnosticos/$chave/mapa'
    | '/admin/diagnosticos/'
    | '/admin/diagnosticos/empresa/$id'
    | '/admin/diagnosticos/lider/$id'
    | '/diagnosticos/$chave/lider/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/korthex-executivo'
    | '/lideranca'
    | '/manifesto'
    | '/metodo'
    | '/performance'
    | '/admin/$id'
    | '/admin/novo'
    | '/blog/$slug'
    | '/diagnosticos/$chave'
    | '/admin'
    | '/blog'
    | '/admin/diagnosticos/$id'
    | '/admin/diagnosticos/resultado-exemplo'
    | '/diagnosticos/$chave/mapa'
    | '/admin/diagnosticos'
    | '/admin/diagnosticos/empresa/$id'
    | '/admin/diagnosticos/lider/$id'
    | '/diagnosticos/$chave/lider/$id'
  id:
    | '__root__'
    | '/'
    | '/korthex-executivo'
    | '/lideranca'
    | '/manifesto'
    | '/metodo'
    | '/performance'
    | '/admin/$id'
    | '/admin/novo'
    | '/blog/$slug'
    | '/diagnosticos/$chave'
    | '/admin/'
    | '/blog/'
    | '/admin/diagnosticos/$id'
    | '/admin/diagnosticos/resultado-exemplo'
    | '/diagnosticos/$chave_/mapa'
    | '/admin/diagnosticos/'
    | '/admin/diagnosticos/empresa/$id'
    | '/admin/diagnosticos/lider/$id'
    | '/diagnosticos/$chave_/lider/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KorthexExecutivoRoute: typeof KorthexExecutivoRoute
  LiderancaRoute: typeof LiderancaRoute
  ManifestoRoute: typeof ManifestoRoute
  MetodoRoute: typeof MetodoRoute
  PerformanceRoute: typeof PerformanceRoute
  AdminIdRoute: typeof AdminIdRoute
  AdminNovoRoute: typeof AdminNovoRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DiagnosticosChaveRoute: typeof DiagnosticosChaveRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  AdminDiagnosticosIdRoute: typeof AdminDiagnosticosIdRoute
  AdminDiagnosticosResultadoExemploRoute: typeof AdminDiagnosticosResultadoExemploRoute
  DiagnosticosChaveMapaRoute: typeof DiagnosticosChaveMapaRoute
  AdminDiagnosticosIndexRoute: typeof AdminDiagnosticosIndexRoute
  AdminDiagnosticosEmpresaIdRoute: typeof AdminDiagnosticosEmpresaIdRoute
  AdminDiagnosticosLiderIdRoute: typeof AdminDiagnosticosLiderIdRoute
  DiagnosticosChaveLiderIdRoute: typeof DiagnosticosChaveLiderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo': {
      id: '/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof MetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lideranca': {
      id: '/lideranca'
      path: '/lideranca'
      fullPath: '/lideranca'
      preLoaderRoute: typeof LiderancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/korthex-executivo': {
      id: '/korthex-executivo'
      path: '/korthex-executivo'
      fullPath: '/korthex-executivo'
      preLoaderRoute: typeof KorthexExecutivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosticos/$chave': {
      id: '/diagnosticos/$chave'
      path: '/diagnosticos/$chave'
      fullPath: '/diagnosticos/$chave'
      preLoaderRoute: typeof DiagnosticosChaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/novo': {
      id: '/admin/novo'
      path: '/admin/novo'
      fullPath: '/admin/novo'
      preLoaderRoute: typeof AdminNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$id': {
      id: '/admin/$id'
      path: '/admin/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AdminIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/diagnosticos/': {
      id: '/admin/diagnosticos/'
      path: '/admin/diagnosticos'
      fullPath: '/admin/diagnosticos/'
      preLoaderRoute: typeof AdminDiagnosticosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosticos/$chave_/mapa': {
      id: '/diagnosticos/$chave_/mapa'
      path: '/diagnosticos/$chave/mapa'
      fullPath: '/diagnosticos/$chave/mapa'
      preLoaderRoute: typeof DiagnosticosChaveMapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/diagnosticos/resultado-exemplo': {
      id: '/admin/diagnosticos/resultado-exemplo'
      path: '/admin/diagnosticos/resultado-exemplo'
      fullPath: '/admin/diagnosticos/resultado-exemplo'
      preLoaderRoute: typeof AdminDiagnosticosResultadoExemploRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/diagnosticos/$id': {
      id: '/admin/diagnosticos/$id'
      path: '/admin/diagnosticos/$id'
      fullPath: '/admin/diagnosticos/$id'
      preLoaderRoute: typeof AdminDiagnosticosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosticos/$chave_/lider/$id': {
      id: '/diagnosticos/$chave_/lider/$id'
      path: '/diagnosticos/$chave/lider/$id'
      fullPath: '/diagnosticos/$chave/lider/$id'
      preLoaderRoute: typeof DiagnosticosChaveLiderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/diagnosticos/lider/$id': {
      id: '/admin/diagnosticos/lider/$id'
      path: '/admin/diagnosticos/lider/$id'
      fullPath: '/admin/diagnosticos/lider/$id'
      preLoaderRoute: typeof AdminDiagnosticosLiderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/diagnosticos/empresa/$id': {
      id: '/admin/diagnosticos/empresa/$id'
      path: '/admin/diagnosticos/empresa/$id'
      fullPath: '/admin/diagnosticos/empresa/$id'
      preLoaderRoute: typeof AdminDiagnosticosEmpresaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KorthexExecutivoRoute: KorthexExecutivoRoute,
  LiderancaRoute: LiderancaRoute,
  ManifestoRoute: ManifestoRoute,
  MetodoRoute: MetodoRoute,
  PerformanceRoute: PerformanceRoute,
  AdminIdRoute: AdminIdRoute,
  AdminNovoRoute: AdminNovoRoute,
  BlogSlugRoute: BlogSlugRoute,
  DiagnosticosChaveRoute: DiagnosticosChaveRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  AdminDiagnosticosIdRoute: AdminDiagnosticosIdRoute,
  AdminDiagnosticosResultadoExemploRoute:
    AdminDiagnosticosResultadoExemploRoute,
  DiagnosticosChaveMapaRoute: DiagnosticosChaveMapaRoute,
  AdminDiagnosticosIndexRoute: AdminDiagnosticosIndexRoute,
  AdminDiagnosticosEmpresaIdRoute: AdminDiagnosticosEmpresaIdRoute,
  AdminDiagnosticosLiderIdRoute: AdminDiagnosticosLiderIdRoute,
  DiagnosticosChaveLiderIdRoute: DiagnosticosChaveLiderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
